### ISSUE TITLE
yyds，iphone7+15.8 success ~~~

### ISSUE THREAD

**Issue by ki11y0u** [straight-tamago/TrollMisaka#13]
use 2.0-Beta-TS1.5.1，The probability of success is not high. Multiple attempts

**Comment by LindgrenRG** [comment]
Did you jailbreak?

**Comment by ki11y0u** [comment]
> Did you jailbreak?

no

**Comment by TrayBer** [comment]
@ki11y0u  2.0-Beta-TS1.5.1 is a ".tipa" file, how to use it (AltStore can't install it)?

**Comment by tzuyu18** [comment]
>  @ki11y0u  2.0-Beta-TS1.5.1 is a ".tipa" file, how to use it (AltStore can't install it)? 

Just rename the extension to ipa. They change it to tipa to detect it as a trollstore app, but this one is funny since we need the app to install trollstore first, so making tipa is useless, haha
