### ISSUE TITLE
"A server with the specified hostname could not be found."

### ISSUE THREAD

**Issue by OctagonIsAnAmazingShape** [straight-tamago/TrollMisaka#4]
After I kopen, installing Trollstore yields that error before it even gets to download the package. It worked the first time but TrollMisaka didn't show me the option to install Trollstore. After I tried to kopen again, my phone rebooted and since then I can't install Trollstore from the keyboard anymore and just get that message.

Tested on an iPhone 7 Plus on 15.8. Tried sideloading several times, rebooting, clean reinstall through IPSW, still doesn't work.

**Comment by JugieNoob** [comment]
What solved the issue? I'm having the same problem.

**Comment by OctagonIsAnAmazingShape** [comment]
I would either reboot or just sideload again from the beginning. It was an anomaly.
