### ISSUE TITLE
"Not a valid name for an app ID"? 

### ISSUE THREAD

**Issue by nkahenn** [straight-tamago/TrollMisaka#9]
Uh, am getting this notif whenever I try to sideload the app:

![image](https://github.com/straight-tamago/TrollMisaka/assets/157300192/5b5e167b-dfd4-4650-bdf7-8e907fe13a0c)

Any help would be appreciated.

**Comment by rrudner** [comment]
The same

**Comment by casungo** [comment]
Same, I tried modifying the app name with Sideloadly but it literaly adds the original name of the app after my modified name. I can't find a solution to this problem...

**Comment by zoidberggr** [comment]
Also have the same problem

**Comment by sirpeep** [comment]
same, pls fix

**Comment by tzuyu18** [comment]
@straight-tamago we will wait for your update on this. Maybe changing the app name won't take much of your time, so if you have time, please release a bug fix. Thank you!

**Comment by LindgrenRG** [comment]
Same. Has anyone found a solution?

**Comment by casungo** [comment]
> Same. Has anyone found a solution?

Nope, I successufly jailbroke my iPhone 7 Plus by first using palera1n and then using the .tipa file

**Comment by LindgrenRG** [comment]
> > Same. Has anyone found a solution?
> 
> Nope, I successufly jailbroke my iPhone 7 Plus by first using palera1n and then using the .tipa file

Damn, i need my banking apps

**Comment by tzuyu18** [comment]
> > > Same. Has anyone found a solution?
> > 
> > Nope, I successufly jailbroke my iPhone 7 Plus by first using palera1n and then using the .tipa file
> 
> Damn, i need my banking apps

You can remove jailbreak after installing trollstore.

**Comment by rrudner** [comment]
Today I tried again the same process with 2.0 Beta
Got this error:
![obraz](https://github.com/straight-tamago/TrollMisaka/assets/80259264/72b06639-81ba-4b2a-9bee-1b6e462da909)
After turning off Windows Defender everything worked perfectly.

**Comment by MohammedNiham** [comment]
happened to me as well. used sideloadly and removed the 2.0 from the app name in advanced option. worked

**Comment by tzuyu18** [comment]
> happened to me as well. used sideloadly and removed the 2.0 from the app name in advanced option. worked

Can you share the ipa?

**Comment by tzuyu18** [comment]
> Today I tried again the same process with 2.0 Beta Got this error: ![obraz](https://private-user-images.githubusercontent.com/80259264/299333732-72b06639-81ba-4b2a-9bee-1b6e462da909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTUyNzgsIm5iZiI6MTcwNjM5NDk3OCwicGF0aCI6Ii84MDI1OTI2NC8yOTkzMzM3MzItNzJiMDY2MzktODFiYS00YjJhLTliZWUtMWI2ZTQ2MmRhOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIyMzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMWExZDRjYzJkOWU2ZTE4YjhmODY1OWYyMWRmYWRiMGMxMGNkNmY1ZjE2NmE1MGMyOWMzMjkyYmU4OTAzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTCbQCwY_gxLCNt2cArzuzx7M9BrSiIBgiZP_yTniMI) After turning off Windows Defender everything worked perfectly.

Tried the sideloady trick to change the name here's the ipa file if someone wants to try https://we.tl/t-HRlwxDKhHt

But I still get an error same as that on your photo but errno=2 even after disabling windows security

**Comment by nkahenn** [comment]
Late reply guys, but used Sideloadly and changed the name - worked fine then.

For Windows Defender, I believe you have to disable the defender and do something with Chrome Downloads as well.

**Comment by tzuyu18** [comment]
I'm using trollmisaka because my home button isn't working for the jailbreak process (iPhone6s+). I still get an error after successfully installing it. I ordered the parts I needed and fixed my home button just to jailbreak and install trollstore, and then I removed the jailbreak.
I think this app should still be on beta.
